### ISSUE TITLE
Great idea, what are the memory limitations?

### ISSUE THREAD

**Issue by FlailAway** [joshr120/PD-Stepper#1]
The ESP32 appears to be limited to around 160KB. After setting up for local wifi, how does one handle data storage?

Streaming data-feed over wifi to a 3D-printer etc., would be a risky effort I would think, so a few GB of memory would be handy to store data in one complete block for it to feed forward.

Driving the blinds is a nice thing, but with closed-loop (terrific addition) greater things would need greater storage memory. No?

I don't do "G" or "YT" to comment there. :)

**Comment by joshr120** [comment]
Instead of storing all of the movements on the devices you would feed them into a buffer (over USB or WiFi etc). Many people have used ESP32's to run CNC machines using this exact premise (See fluid NC for example). And the common GRBL software runs on an Arduino Uno which has significantly less memory, so I do not think this is an issue if you implement it correctly
